### ISSUE TITLE
Cannot read properties of null (reading 'getLatLng')

### ISSUE THREAD

**Issue by fear4good** [fear4good/projectweb#2]
Markers sometimes don't show when the site is loaded for the first time, cause of the getLatLng being null.
After a refresh the error goes away.
Error Message:
Uncaught TypeError: Cannot read properties of null (reading 'getLatLng')
    at map-leaflet.js:76:46
    at Array.forEach (<anonymous>)
    at filterMarkers (map-leaflet.js:68:19)
    at Object.success (map-leaflet.js:184:7)
    at c (jquery-3.7.0.min.js:2:25266)
    at Object.fireWith [as resolveWith] (jquery-3.7.0.min.js:2:26015)
    at l (jquery-3.7.0.min.js:2:77721)
    at XMLHttpRequest.<anonymous> (jquery-3.7.0.min.js:2:80204)

**Comment by fear4good** [comment]
added an if loop that calls the function again if e.Latlng is null
